function generatePath(value) {
  return `//mat-option[normalize-space()='${value}']`;
}

module.exports = {
  HOI_SO_NH_KIEN_LONG: generatePath('HOI SO NH KIEN LONG'),
  CN_KHANH_HOA: generatePath('KLB - CN KHANH HOA'),
  PGD_CAI_RANG: generatePath('KLB - PGD CAI RANG'),
  PGD_HAI_CHAU: generatePath('KLB - PGD HAI CHAU'),
  PGD_PHAM_HUNG: generatePath('KLB - PGD PHAM HUNG'),
  PGD_PHUNG_HIEP: generatePath('KLB - PGD PHUNG HIEP'),
  CN_RACH_GIA: generatePath('KLB - CN RACH GIA'),
  CN_VINH_LONG: generatePath('KLB - CN VINH LONG'),
  PGD_GO_VAP: generatePath('KLB - PGD GO VAP'),
  PGD_BINH_TAY: generatePath('KLB - PGD BINH TAY'),
  PGD_PHU_NHUAN: generatePath('KLB - PGD PHU NHUAN'),
  PGD_TRAN_NGUYEN_HAN: generatePath('KLB - PGD TRAN NGUYEN HAN'),
  PGD_NGO_QUYEN: generatePath('KLB - PGD NGO QUYEN'),
  PGD_LACH_TRAY: generatePath('KLB - PGD LACH TRAY'),
  CN_HAI_PHONG: generatePath('KLB - CN HAI PHONG'),
  PGD_DIEN_KHANH: generatePath('KLB - PGD DIEN KHANH'),
  CN_BINH_DUONG: generatePath('KLB - CN BINH DUONG'),
  PGD_HONG_DAN: generatePath('KLB - PGD HONG DAN'),
  PGD_BA_TRI: generatePath('KLB - PGD BA TRI'),
  CN_CAN_THO: generatePath('KLB - CN CAN THO'),
  PGD_O_MON: generatePath('KLB - PGD O MON'),
  PGD_THOT_NOT: generatePath('KLB - PGD THOT NOT'),
  CN_DA_NANG: generatePath('KLB - CN DA NANG'),
  PGD_SONG_HAN: generatePath('KLB - PGD SONG HAN'),
  CN_DONG_THAP: generatePath('KLB - CN DONG THAP'),
  PGD_SA_DEC: generatePath('KLB - PGD SA DEC'),
  CN_HA_NOI: generatePath('KLB - CN HA NOI'),
  PGD_TAY_HO: generatePath('KLB - PGD TAY HO'),
  PGD_LONG_MY: generatePath('KLB - PGD LONG MY'),
  PGD_RACH_SOI: generatePath('KLB - PGD RACH SOI'),
  CN_SAI_GON: generatePath('KLB - CN SAI GON'),
  CN_BAC_LIEU: generatePath('KLB - CN BAC LIEU'),
  PGD_HONG_NGU: generatePath('KLB - PGD HONG NGU'),
  CN_DAK_LAK: generatePath('KLB - CN DAK LAK'),
  PGD_TAN_LAP: generatePath('KLB - PGD TAN LAP'),
  CN_HAU_GIANG: generatePath('KLB - CN HAU GIANG'),
  PGD_KINH_8: generatePath('KLB - PGD KINH 8'),
  PGD_SO_2: generatePath('KLB - PGD SO 2'),
  PGD_SO_4: generatePath('KLB - PGD SO 4'),
  PGD_HA_TIEN: generatePath('KLB - PGD HA TIEN'),
  PGD_BEN_NHUT: generatePath('KLB - PGD BEN NHUT'),
  PGD_SO_3: generatePath('KLB - PGD SO 3'),
  PGD_BINH_MINH: generatePath('KLB - PGD BINH MINH'),
  PGD_CANG_LONG: generatePath('KLB - PGD CANG LONG'),
  PGD_TIEU_CAN: generatePath('KLB - PGD TIEU CAN'),
  PGD_LAI_THIEU: generatePath('KLB - PGD LAI THIEU'),
  PGD_BEN_CAT: generatePath('KLB - PGD BEN CAT'),
  PGD_HO_PHONG: generatePath('KLB - PGD HO PHONG'),
  CN_BEN_TRE: generatePath('KLB - CN BEN TRE'),
  PGD_BA_DINH: generatePath('KLB - PGD BA DINH'),
  PGD_DUYEN_HAI: generatePath('KLB - PGD DUYEN HAI'),
  CN_TRA_VINH: generatePath('KLB - CN TRA VINH'),
  PGD_TUNG_THIEN_VUONG: generatePath('KLB - PGD TUNG THIEN VUONG'),
  PGD_TAN_SON_NHI: generatePath('KLB - PGD TAN SON NHI'),
  PGD_BA_CHIEU: generatePath('KLB - PGD BA CHIEU'),
  PGD_THU_DUC: generatePath('KLB - PGD THU DUC'),
  PGD_QUAN_12: generatePath('KLB - PGD QUAN 12'),
  PGD_DAM_SEN: generatePath('KLB - PGD DAM SEN'),
  PGD_NGO_GIA_TU: generatePath('KLB - PGD NGO GIA TU'),
  PGD_AN_LAC: generatePath('KLB - PGD AN LAC'),
  PGD_VINH_HAI: generatePath('KLB - PGD VINH HAI'),
  PGD_NINH_HOA: generatePath('KLB - PGD NINH HOA'),
  PGD_CAM_RANH: generatePath('KLB - PGD CAM RANH'),
  CN_CA_MAU: generatePath('KLB - CN CA MAU'),
  PGD_AN_MINH: generatePath('KLB - PGD AN MINH'),
  CN_SOC_TRANG: generatePath('KLB - CN SOC TRANG'),
  PGD_TAM_QUAN: generatePath('KLB - PGD TAM QUAN'),
  NEO_BRANCH: generatePath('NEO BRANCH'),
  PGD_THOAI_SON: generatePath('KLB - PGD THOAI SON'),
  CN_PHU_YEN: generatePath('KLB - CN PHU YEN'),
  CN_BA_RIA_VUNG_TAU: generatePath('KLB - CN BA RIA - VUNG TAU'),
  PGD_TAN_AN: generatePath('KLB - PGD TAN AN'),
  PGD_DAM_DOI: generatePath('KLB - PGD DAM DOI'),
  CN_TAY_NINH: generatePath('KLB - CN TAY NINH'),
  PGD_DUC_HOA: generatePath('KLB - PGD DUC HOA'),
  PGD_THAP_MUOI: generatePath('KLB - PGD THAP MUOI'),
  PGD_NGA_BAY: generatePath('KLB - PGD NGA BAY'),
  PGD_TRA_QUYT: generatePath('KLB - PGD TRA QUYT'),
  PGD_LONG_THANH: generatePath('KLB - PGD LONG THANH'),
  CN_QUANG_NAM: generatePath('KLB - CN QUANG NAM'),
  PGD_TAN_CHAU: generatePath('KLB - PGD TAN CHAU'),
  CN_AN_GIANG: generatePath('KLB - CN AN GIANG'),
  PGD_VINH_THUAN: generatePath('KLB - PGD VINH THUAN'),
  PGD_AN_BIEN: generatePath('KLB - PGD AN BIEN'),
  PGD_GO_QUAO: generatePath('KLB - PGD GO QUAO'),
  PGD_PHUOC_LONG: generatePath('KLB - PGD PHUOC LONG'),
  PGD_MO_CAY_NAM: generatePath('KLB - PGD MO CAY NAM'),
  PGD_DI_AN: generatePath('KLB - PGD DI AN'),
  CN_TIEN_GIANG: generatePath('KLB - CN TIEN GIANG'),
  CN_BINH_THUAN: generatePath('KLB - CN BINH THUAN'),
  PGD_CUKUIN: generatePath('KLB - PGD CUKUIN'),
  PGD_AN_NHON: generatePath('KLB - PGD AN NHON'),
  PGD_PHU_MY: generatePath('KLB - PGD PHU MY'),
  PGD_THANH_TRI: generatePath('KLB - PGD THANH TRI'),
  PGD_HAM_TIEN: generatePath('KLB - PGD HAM TIEN'),
  PGD_VAN_NINH: generatePath('KLB - PGD VAN NINH'),
  PGD_BUON_HO: generatePath('KLB - PGD BUON HO'),
  PGD_THOI_BINH: generatePath('KLB - PGD THOI BINH'),
  PGD_CAI_BE: generatePath('KLB - PGD CAI BE'),
  PGD_VUNG_LIEM: generatePath('KLB - PGD VUNG LIEM'),
  CN_CAN_GIO: generatePath('KLB - CN CAN GIO'),
  PGD_CHAU_THANH: generatePath('KLB - PGD CHAU THANH'),
  PGD_LONG_KHANH: generatePath('KLB - PGD LONG KHANH'),
  PGD_BINH_DAI: generatePath('KLB - PGD BINH DAI'),
  PGD_HON_DAT: generatePath('KLB - PGD HON DAT'),
  PGD_BINH_THUY: generatePath('KLB - PGD BINH THUY'),
  PGD_VINH_CHAU: generatePath('KLB - PGD VINH CHAU'),
  PGD_SONG_CA: generatePath('KLB - PGD SONG CAU'),
  PGD_CAI_LAY: generatePath('KLB - PGD CAI LAY'),
  CN_DONG_NAI: generatePath('KLB - CN DONG NAI'),
  PGD_VINH_THANH: generatePath('KLB - PGD VINH THANH'),
  PGD_DONG_DO: generatePath('KLB - PGD DONG DO'),
  PGD_NAM_CAN: generatePath('KLB - PGD NAM CAN'),
  CN_LAM_DONG: generatePath('KLB - CN LAM DONG'),
  PGD_SON_HOA: generatePath('KLB - PGD SON HOA'),
  PGD_TUY_AN: generatePath('KLB - PGD TUY AN'),
  PGD_TRANG_BANG: generatePath('KLB - PGD TRANG BANG'),
  PGD_LONG_DIEN: generatePath('KLB - PGD LONG DIEN'),
  PGD_TAN_HIEP: generatePath('KLB - PGD TAN HIEP'),
  PGD_QUAN_7: generatePath('KLB - PGD QUAN 7'),
  CN_LONG_AN: generatePath('KLB - CN LONG AN'),
  PGD_BINH_TAN: generatePath('KLB - PGD BINH TAN'),
  CN_BINH_DINH: generatePath('KLB - CN BINH DINH'),
  PGD_LAGI: generatePath('KLB - PGD LAGI'),
  PGD_CHAU_DOC: generatePath('KLB - PGD CHAU DOC'),
  PGD_TAN_THANH: generatePath('KLB - PGD TAN THANH'),
  CN_PHU_QUOC: generatePath('KLB - CN PHU QUOC'),
  PGD_AN_THOI: generatePath('KLB - PGD AN THOI'),
  PGD_KIEN_AN: generatePath('KLB - PGD KIEN AN'),
  PGD_GO_CONG: generatePath('KLB - PGD GO CONG'),
  PGD_CAN_GIUOC: generatePath('KLB - PGD CAN GIUOC'),
  CN_NHA_BE: generatePath('KLB - CN NHA BE'),
  PGD_VUNG_TAU: generatePath('KLB - PGD VUNG TAU'),
  PGD_TRA_ON: generatePath('KLB - PGD TRA ON'),
  PGD_NGU_HANH_SON: generatePath('KLB - PGD NGU HANH SON'),
  PGD_BAC_BINH: generatePath('KLB - PGD BAC BINH'),
};
